- name: HomeLab
  hide-desktop-navigation: true
  center-vertically: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: custom-api
          title: Immich stats
          cache: 1d
          url: ${IMMICH_EXTERNAL_URL}/api/server/statistics
          headers:
            x-api-key: ${IMMICH_API_KEY}
            Accept: application/json
          template: |
            <div class="flex justify-between text-center">
              <div>
                  <div class="color-highlight size-h3">{{ .JSON.Int "photos" | formatNumber }}</div>
                  <div class="size-h6">PHOTOS</div>
              </div>
              <div>
                  <div class="color-highlight size-h3">{{ .JSON.Int "videos" | formatNumber }}</div>
                  <div class="size-h6">VIDEOS</div>
              </div>
              <div>
                  <div class="color-highlight size-h3">{{ div (.JSON.Int "usage" | toFloat) 1073741824 | toInt | formatNumber }}GB</div>
                  <div class="size-h6">USAGE</div>
              </div>
            </div>

    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: AI
          sites:
            - title: ChatGPT
              url: https://chat.openai.com
              icon: si:openai

        - type: monitor
          cache: 1m
          title: External
          sites:
            - title: Home Assistant
              url: ${HA_EXTERNAL_URL}
              icon: si:homeassistant
            - title: ESPHome
              url: ${ESPH_EXTERNAL_URL}
              icon: si:esphome
            - title: Frigate
              url: ${FRIGATE_EXTERNAL_URL}
              icon: si:gitea
            - title: Zigbee2MQTT
              url: ${Z2M_EXTERNAL_URL}
              icon: si:zigbee2mqtt
            - title: Immich
              url: ${IMMICH_EXTERNAL_URL}
              icon: si:immich
            - title: Vaultwarden
              url: ${VWARDEN_EXTERNAL_URL}
              icon: si:vaultwarden
            - title: Docmost
              url: ${DOCMOST_EXTERNAL_URL}
              icon: si:googledocs

        - type: monitor
          cache: 1m
          title: Internal
          sites:
            - title: Home Assistant
              url: ${HA_URL}
              icon: si:homeassistant
            - title: ESPHome
              url: ${ESPH_URL}
              icon: si:esphome
            - title: Frigate
              url: ${FRIGATE_URL}
              icon: si:gitea
            - title: Zigbee2MQTT
              url: ${Z2M_URL}
              icon: si:zigbee2mqtt
            - title: Immich
              url: ${IMMICH_URL}
              icon: si:immich
            - title: Vaultwarden
              url: ${VWARDEN_URL}
              icon: si:vaultwarden
            - title: Docmost
              url: ${DOCMOST_URL}
              icon: si:googledocs
    
        - type: reddit
          subreddit: Tailscale
          style: horizontal-cards
        - type: reddit
          subreddit: homeassistant
          style: horizontal-cards

    - size: small
      widgets:
        - type: weather
          location: ${LOCATION}
          units: metric
          hour-format: 24h

        

        - type: releases
          show-source-icon: true
          repositories:
            - immich-app/immich
            - home-assistant/home-assistant
            - tailscale/tailscale
            - blakeblackshear/frigate
            - Koenkk/zigbee2mqtt
            - dani-garcia/vaultwarden
            - esphome/esphome